/* KikoMix — Project TriBeam: mock catalog data layer.
 * Sets window.KM_DATA = { tracks: [...] }.
 *
 * ALL TRACKS ARE MOCK. Artist names are invented; nothing here represents a
 * real recording or a real chart hit. In production this data comes from the
 * provider adapters (see adapters.js), not from a static file.
 *
 * STEM-SEPARATION NOTE: Multi-Form stem separation is only enabled for the
 * single public-domain-style classical track t032 ("Moonlight Sonata (Solo
 * Piano)"), which ships via the local-files adapter. All other tracks
 * return requiresAuth / simulated from resolve().
 */
(function () {
  'use strict';

  var TRACKS = [
    // ---------- POP ----------
    { id:'t001', title:'Neon Confetti', artist:'Cassidy Bloom', album:'Glitter Parade',
      durationSec:214, genre:'pop', mood:'happy', tempoBpm:118, era:'2020s', energy:8,
      instruments:['synth','drums','bass','vocals'], sources:['spotify','apple','youtube'],
      hue:320, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:45},{name:'Verse',at:78},{name:'Chorus',at:105},{name:'Bridge',at:140},{name:'Chorus',at:168},{name:'Outro',at:195}] },
    { id:'t002', title:'Midnight Postcard', artist:'The Paper Comets', album:'Overnight',
      durationSec:189, genre:'pop', mood:'chill', tempoBpm:92, era:'2010s', energy:5,
      instruments:['guitar','piano','drums','vocals'], sources:['spotify','apple'],
      hue:210, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:48},{name:'Verse',at:80},{name:'Chorus',at:110},{name:'Bridge',at:142},{name:'Outro',at:172}] },
    { id:'t003', title:'Static Valentine', artist:'Vera Lane', album:'Frequency of Us',
      durationSec:201, genre:'pop', mood:'energetic', tempoBpm:128, era:'2020s', energy:9,
      instruments:['synth','drums','bass','vocals'], sources:['spotify','youtube','soundcloud'],
      hue:350, sections:[{name:'Intro',at:0},{name:'Verse',at:10},{name:'Chorus',at:38},{name:'Drop',at:90},{name:'Chorus',at:120},{name:'Bridge',at:155},{name:'Outro',at:186}] },
    { id:'t004', title:'Glue & Glitter', artist:'Cassidy Bloom', album:'Glitter Parade',
      durationSec:226, genre:'pop', mood:'happy', tempoBpm:104, era:'2020s', energy:7,
      instruments:['synth','guitar','drums','vocals'], sources:['spotify'],
      hue:35, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:52},{name:'Verse',at:88},{name:'Chorus',at:120},{name:'Bridge',at:160},{name:'Chorus',at:190},{name:'Outro',at:212}] },
    { id:'t005', title:'Paper Plane Hearts', artist:'Aero Wex', album:'Terminal 3',
      durationSec:178, genre:'pop', mood:'chill', tempoBpm:98, era:'2010s', energy:5,
      instruments:['piano','strings','vocals'], sources:['apple','youtube'],
      hue:190, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:44},{name:'Verse',at:76},{name:'Chorus',at:104},{name:'Bridge',at:134},{name:'Outro',at:162}] },
    { id:'t006', title:'Sunset Checkout', artist:'The Paper Comets', album:'Overnight',
      durationSec:205, genre:'pop', mood:'driving', tempoBpm:122, era:'2010s', energy:7,
      instruments:['guitar','drums','bass','vocals'], sources:['youtube'],
      hue:25, sections:[{name:'Intro',at:0},{name:'Verse',at:11},{name:'Chorus',at:42},{name:'Verse',at:74},{name:'Chorus',at:102},{name:'Solo',at:138},{name:'Chorus',at:162},{name:'Outro',at:190}] },

    // ---------- ROCK ----------
    { id:'t007', title:'Gravel Anthem', artist:'Rust & Reverie', album:'Barnstormers',
      durationSec:243, genre:'rock', mood:'energetic', tempoBpm:142, era:'1990s', energy:9,
      instruments:['guitar','drums','bass','vocals'], sources:['spotify','apple','youtube'],
      hue:10, sections:[{name:'Intro',at:0},{name:'Verse',at:18},{name:'Chorus',at:55},{name:'Verse',at:95},{name:'Chorus',at:130},{name:'Solo',at:165},{name:'Chorus',at:200},{name:'Outro',at:228}] },
    { id:'t008', title:'Old Neon Highway', artist:'The Dusk Riders', album:'Mile Marker 9',
      durationSec:218, genre:'rock', mood:'driving', tempoBpm:136, era:'1970s', energy:8,
      instruments:['guitar','drums','bass','harmonica','vocals'], sources:['spotify','apple'],
      hue:20, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:50},{name:'Verse',at:85},{name:'Chorus',at:118},{name:'Bridge',at:152},{name:'Chorus',at:182},{name:'Outro',at:205}] },
    { id:'t009', title:'Concrete Garden', artist:'Rust & Reverie', album:'Barnstormers',
      durationSec:231, genre:'rock', mood:'melancholy', tempoBpm:108, era:'2000s', energy:6,
      instruments:['guitar','drums','piano','vocals'], sources:['spotify','soundcloud'],
      hue:200, sections:[{name:'Intro',at:0},{name:'Verse',at:20},{name:'Chorus',at:62},{name:'Verse',at:100},{name:'Chorus',at:138},{name:'Bridge',at:175},{name:'Outro',at:214}] },
    { id:'t010', title:'Fossil Fuel Fable', artist:'The Dusk Riders', album:'Mile Marker 9',
      durationSec:196, genre:'rock', mood:'energetic', tempoBpm:150, era:'1980s', energy:9,
      instruments:['guitar','drums','bass','vocals'], sources:['youtube'],
      hue:55, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:44},{name:'Verse',at:76},{name:'Chorus',at:106},{name:'Solo',at:136},{name:'Chorus',at:162},{name:'Outro',at:184}] },
    { id:'t011', title:'Velvet Sledgehammer', artist:'Iron Petal', album:'Petal to the Metal',
      durationSec:224, genre:'rock', mood:'driving', tempoBpm:132, era:'2010s', energy:8,
      instruments:['guitar','drums','bass','vocals'], sources:['apple','youtube','soundcloud'],
      hue:340, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:52},{name:'Verse',at:88},{name:'Chorus',at:122},{name:'Bridge',at:158},{name:'Chorus',at:188},{name:'Outro',at:210}] },
    { id:'t012', title:'Amber Static', artist:'Iron Petal', album:'Petal to the Metal',
      durationSec:187, genre:'rock', mood:'chill', tempoBpm:96, era:'2020s', energy:4,
      instruments:['guitar','bass','drums','vocals'], sources:['soundcloud'],
      hue:160, sections:[{name:'Intro',at:0},{name:'Verse',at:18},{name:'Chorus',at:56},{name:'Verse',at:92},{name:'Chorus',at:126},{name:'Bridge',at:156},{name:'Outro',at:174}] },

    // ---------- HIP-HOP ----------
    { id:'t013', title:'Payday Poems', artist:'MC Ledger', album:'Cash Register Blues',
      durationSec:192, genre:'hip-hop', mood:'energetic', tempoBpm:95, era:'2010s', energy:8,
      instruments:['drums','bass','synth','vocals'], sources:['spotify','apple','youtube','soundcloud'],
      hue:45, sections:[{name:'Intro',at:0},{name:'Verse',at:10},{name:'Chorus',at:48},{name:'Verse',at:80},{name:'Chorus',at:116},{name:'Bridge',at:148},{name:'Outro',at:178}] },
    { id:'t014', title:'Cobblestone Chorus', artist:'Penny Cipher', album:'Margin Notes',
      durationSec:207, genre:'hip-hop', mood:'focus', tempoBpm:88, era:'2000s', energy:6,
      instruments:['drums','piano','bass','vocals'], sources:['spotify','youtube'],
      hue:265, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:52},{name:'Verse',at:90},{name:'Chorus',at:126},{name:'Bridge',at:162},{name:'Outro',at:192}] },
    { id:'t015', title:'Laundromat Letters', artist:'MC Ledger', album:'Cash Register Blues',
      durationSec:181, genre:'hip-hop', mood:'chill', tempoBpm:82, era:'2020s', energy:5,
      instruments:['piano','drums','bass','vocals'], sources:['apple'],
      hue:180, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:46},{name:'Verse',at:78},{name:'Chorus',at:110},{name:'Bridge',at:142},{name:'Outro',at:168}] },
    { id:'t016', title:'Brick by Rhyme', artist:'The Corner Poets', album:'Cypher Season',
      durationSec:199, genre:'hip-hop', mood:'driving', tempoBpm:92, era:'1990s', energy:7,
      instruments:['drums','synth','vocals'], sources:['spotify','soundcloud'],
      hue:15, sections:[{name:'Intro',at:0},{name:'Verse',at:8},{name:'Chorus',at:44},{name:'Verse',at:78},{name:'Chorus',at:112},{name:'Bridge',at:146},{name:'Chorus',at:168},{name:'Outro',at:188}] },
    { id:'t017', title:'Lo-Fi Lunch Break', artist:'Penny Cipher', album:'Margin Notes',
      durationSec:174, genre:'hip-hop', mood:'focus', tempoBpm:84, era:'2020s', energy:4,
      instruments:['piano','drums','vocals'], sources:['soundcloud','youtube'],
      hue:150, sections:[{name:'Intro',at:0},{name:'Verse',at:10},{name:'Chorus',at:42},{name:'Verse',at:74},{name:'Chorus',at:104},{name:'Bridge',at:132},{name:'Outro',at:160}] },

    // ---------- ELECTRONIC ----------
    { id:'t018', title:'Glass Elevator', artist:'Neon Vesper', album:'High-Rise Dreams',
      durationSec:236, genre:'electronic', mood:'chill', tempoBpm:100, era:'2010s', energy:6,
      instruments:['synth','drums','pads'], sources:['spotify','apple','youtube'],
      hue:220, sections:[{name:'Intro',at:0},{name:'Verse',at:24},{name:'Chorus',at:70},{name:'Verse',at:112},{name:'Chorus',at:150},{name:'Bridge',at:188},{name:'Outro',at:220}] },
    { id:'t019', title:'Bassline Commute', artist:'Metro Bloom', album:'Rush Hour EP',
      durationSec:198, genre:'electronic', mood:'driving', tempoBpm:128, era:'2020s', energy:8,
      instruments:['synth','drums','bass'], sources:['spotify','youtube','soundcloud'],
      hue:300, sections:[{name:'Intro',at:0},{name:'Drop',at:30},{name:'Chorus',at:66},{name:'Drop',at:102},{name:'Bridge',at:138},{name:'Chorus',at:162},{name:'Outro',at:186}] },
    { id:'t020', title:'Subway Supernova', artist:'Neon Vesper', album:'High-Rise Dreams',
      durationSec:221, genre:'electronic', mood:'energetic', tempoBpm:134, era:'2020s', energy:9,
      instruments:['synth','drums','bass','pads'], sources:['apple','soundcloud'],
      hue:280, sections:[{name:'Intro',at:0},{name:'Verse',at:20},{name:'Drop',at:58},{name:'Chorus',at:96},{name:'Drop',at:132},{name:'Bridge',at:168},{name:'Outro',at:206}] },
    { id:'t021', title:'Laser Tag Lullaby', artist:'Poly Fawn', album:'Soft Circuits',
      durationSec:203, genre:'electronic', mood:'happy', tempoBpm:112, era:'2000s', energy:7,
      instruments:['synth','drums','vocals'], sources:['spotify'],
      hue:330, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:54},{name:'Verse',at:90},{name:'Chorus',at:126},{name:'Bridge',at:162},{name:'Outro',at:190}] },
    { id:'t022', title:'Analog Astronaut', artist:'Metro Bloom', album:'Rush Hour EP',
      durationSec:247, genre:'electronic', mood:'focus', tempoBpm:118, era:'2010s', energy:6,
      instruments:['synth','bass','pads'], sources:['youtube'],
      hue:200, sections:[{name:'Intro',at:0},{name:'Verse',at:28},{name:'Chorus',at:76},{name:'Verse',at:120},{name:'Chorus',at:164},{name:'Bridge',at:202},{name:'Outro',at:232}] },
    { id:'t023', title:'Fog Machine Fable', artist:'Poly Fawn', album:'Soft Circuits',
      durationSec:215, genre:'electronic', mood:'chill', tempoBpm:90, era:'2020s', energy:5,
      instruments:['synth','pads','vocals'], sources:['soundcloud','apple'],
      hue:250, sections:[{name:'Intro',at:0},{name:'Verse',at:22},{name:'Chorus',at:64},{name:'Verse',at:104},{name:'Chorus',at:144},{name:'Bridge',at:180},{name:'Outro',at:202}] },

    // ---------- JAZZ ----------
    { id:'t024', title:'Blue Umbrella', artist:'The Marlowe Five', album:'Raincheck',
      durationSec:264, genre:'jazz', mood:'chill', tempoBpm:72, era:'1960s', energy:4,
      instruments:['saxophone','piano','bass','drums'], sources:['spotify','apple'],
      hue:205, sections:[{name:'Intro',at:0},{name:'Verse',at:24},{name:'Chorus',at:78},{name:'Solo',at:130},{name:'Verse',at:182},{name:'Chorus',at:222},{name:'Outro',at:250}] },
    { id:'t025', title:'Cotton Club Carousel', artist:'Ada Rivers', album:'Second Set',
      durationSec:238, genre:'jazz', mood:'happy', tempoBpm:132, era:'1970s', energy:7,
      instruments:['trumpet','piano','bass','drums','vocals'], sources:['spotify','youtube'],
      hue:45, sections:[{name:'Intro',at:0},{name:'Verse',at:20},{name:'Chorus',at:66},{name:'Solo',at:110},{name:'Chorus',at:150},{name:'Verse',at:190},{name:'Outro',at:224}] },
    { id:'t026', title:'Half-Light Harbor', artist:'The Marlowe Five', album:'Raincheck',
      durationSec:281, genre:'jazz', mood:'melancholy', tempoBpm:66, era:'1980s', energy:3,
      instruments:['saxophone','piano','bass'], sources:['apple'],
      hue:230, sections:[{name:'Intro',at:0},{name:'Verse',at:30},{name:'Chorus',at:90},{name:'Solo',at:150},{name:'Verse',at:210},{name:'Outro',at:266}] },
    { id:'t027', title:'Espresso Syncopation', artist:'Ada Rivers', album:'Second Set',
      durationSec:222, genre:'jazz', mood:'energetic', tempoBpm:158, era:'1960s', energy:8,
      instruments:['trumpet','piano','drums','bass'], sources:['youtube','soundcloud'],
      hue:30, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:58},{name:'Solo',at:100},{name:'Chorus',at:142},{name:'Verse',at:182},{name:'Outro',at:208}] },
    { id:'t028', title:'Velvet Downbeat', artist:'Trio Northbound', album:'Night Ferry',
      durationSec:256, genre:'jazz', mood:'focus', tempoBpm:88, era:'2000s', energy:5,
      instruments:['guitar','bass','drums'], sources:['spotify','soundcloud','apple'],
      hue:170, sections:[{name:'Intro',at:0},{name:'Verse',at:26},{name:'Chorus',at:80},{name:'Solo',at:134},{name:'Chorus',at:188},{name:'Outro',at:240}] },

    // ---------- CLASSICAL ----------
    { id:'t029', title:'Cello in the Rain', artist:'Mock Orchestra', album:'Studio Sessions Vol. 2',
      durationSec:312, genre:'classical', mood:'melancholy', tempoBpm:60, era:'2010s', energy:3,
      instruments:['cello','violin','piano'], sources:['spotify','apple'],
      hue:240, sections:[{name:'Intro',at:0},{name:'Verse',at:36},{name:'Chorus',at:104},{name:'Bridge',at:180},{name:'Chorus',at:240},{name:'Outro',at:296}] },
    { id:'t030', title:'Brass at Dawn', artist:'Harbor Winds', album:'Morning Repertoire',
      durationSec:274, genre:'classical', mood:'happy', tempoBpm:104, era:'1990s', energy:6,
      instruments:['trumpet','trombone','tuba','percussion'], sources:['youtube'],
      hue:50, sections:[{name:'Intro',at:0},{name:'Verse',at:30},{name:'Chorus',at:92},{name:'Verse',at:150},{name:'Chorus',at:208},{name:'Outro',at:258}] },
    { id:'t031', title:'Paper Moon Minuet', artist:'Mock Orchestra', album:'Studio Sessions Vol. 2',
      durationSec:198, genre:'classical', mood:'focus', tempoBpm:84, era:'2000s', energy:4,
      instruments:['violin','viola','cello'], sources:['apple'],
      hue:190, sections:[{name:'Intro',at:0},{name:'Verse',at:22},{name:'Chorus',at:66},{name:'Verse',at:108},{name:'Chorus',at:150},{name:'Outro',at:184}] },
    { id:'t032', title:'Moonlight Sonata (Solo Piano)', artist:'Heritage Ensemble', album:'Public Domain Classics',
      durationSec:342, genre:'classical', mood:'melancholy', tempoBpm:54, era:'2020s', energy:3,
      instruments:['piano'], sources:['local'],
      hue:225, sections:[{name:'Intro',at:0},{name:'Verse',at:30},{name:'Chorus',at:100},{name:'Bridge',at:190},{name:'Verse',at:260},{name:'Outro',at:320}] },

    // ---------- R&B ----------
    { id:'t033', title:'Honey & Smoke', artist:'Velvet June', album:'Slow Burn',
      durationSec:213, genre:'R&B', mood:'chill', tempoBpm:88, era:'2010s', energy:6,
      instruments:['vocals','piano','bass','drums'], sources:['spotify','apple','youtube'],
      hue:15, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:52},{name:'Verse',at:88},{name:'Chorus',at:124},{name:'Bridge',at:162},{name:'Outro',at:198}] },
    { id:'t034', title:'Velvet Voicemail', artist:'Dre Apollo', album:'After Hours FM',
      durationSec:226, genre:'R&B', mood:'melancholy', tempoBpm:76, era:'2020s', energy:5,
      instruments:['vocals','synth','bass'], sources:['spotify','apple'],
      hue:270, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:56},{name:'Verse',at:94},{name:'Chorus',at:132},{name:'Bridge',at:172},{name:'Outro',at:210}] },
    { id:'t035', title:'Chrome Cadillac', artist:'Velvet June', album:'Slow Burn',
      durationSec:201, genre:'R&B', mood:'driving', tempoBpm:102, era:'1990s', energy:7,
      instruments:['vocals','guitar','bass','drums'], sources:['spotify'],
      hue:40, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:48},{name:'Verse',at:82},{name:'Chorus',at:114},{name:'Bridge',at:152},{name:'Outro',at:186}] },
    { id:'t036', title:'Low Light Love', artist:'Dre Apollo', album:'After Hours FM',
      durationSec:218, genre:'R&B', mood:'happy', tempoBpm:96, era:'2020s', energy:6,
      instruments:['vocals','piano','drums'], sources:['apple','youtube'],
      hue:330, sections:[{name:'Intro',at:0},{name:'Verse',at:15},{name:'Chorus',at:54},{name:'Verse',at:90},{name:'Chorus',at:126},{name:'Bridge',at:166},{name:'Outro',at:202}] },
    { id:'t037', title:'Satin & Static', artist:'June & the Currents', album:'Slow Burn',
      durationSec:209, genre:'R&B', mood:'focus', tempoBpm:84, era:'2000s', energy:5,
      instruments:['vocals','guitar','synth'], sources:['soundcloud'],
      hue:190, sections:[{name:'Intro',at:0},{name:'Verse',at:13},{name:'Chorus',at:50},{name:'Verse',at:86},{name:'Chorus',at:122},{name:'Bridge',at:158},{name:'Outro',at:194}] },

    // ---------- INDIE ----------
    { id:'t038', title:'Thrift Store Ghosts', artist:'Cardboard Arcade', album:'Basement Tapes',
      durationSec:197, genre:'indie', mood:'melancholy', tempoBpm:100, era:'2010s', energy:5,
      instruments:['guitar','drums','bass','vocals'], sources:['spotify','youtube','soundcloud'],
      hue:260, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:50},{name:'Verse',at:84},{name:'Chorus',at:118},{name:'Bridge',at:152},{name:'Outro',at:182}] },
    { id:'t039', title:'Faded Film Festival', artist:'The Lanternflies', album:'Porch Light',
      durationSec:184, genre:'indie', mood:'happy', tempoBpm:116, era:'2020s', energy:7,
      instruments:['guitar','vocals','drums'], sources:['spotify','apple'],
      hue:60, sections:[{name:'Intro',at:0},{name:'Verse',at:12},{name:'Chorus',at:44},{name:'Verse',at:76},{name:'Chorus',at:106},{name:'Bridge',at:140},{name:'Outro',at:170}] },
    { id:'t040', title:'Cardboard Castles', artist:'Cardboard Arcade', album:'Basement Tapes',
      durationSec:206, genre:'indie', mood:'chill', tempoBpm:92, era:'2020s', energy:4,
      instruments:['guitar','piano','vocals'], sources:['soundcloud'],
      hue:150, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:54},{name:'Verse',at:90},{name:'Chorus',at:126},{name:'Bridge',at:162},{name:'Outro',at:192}] },
    { id:'t041', title:'Mixtape for Mara', artist:'The Lanternflies', album:'Porch Light',
      durationSec:176, genre:'indie', mood:'happy', tempoBpm:108, era:'2010s', energy:6,
      instruments:['guitar','bass','drums','vocals'], sources:['youtube','local'],
      hue:95, sections:[{name:'Intro',at:0},{name:'Verse',at:10},{name:'Chorus',at:40},{name:'Verse',at:72},{name:'Chorus',at:102},{name:'Bridge',at:134},{name:'Outro',at:162}] },

    // ---------- LATIN ----------
    { id:'t042', title:'Café con Ritmo', artist:'Los Ficticios', album:'Plaza Central',
      durationSec:212, genre:'latin', mood:'happy', tempoBpm:104, era:'1990s', energy:8,
      instruments:['guitar','trumpet','percussion','vocals'], sources:['spotify','apple','youtube'],
      hue:35, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:52},{name:'Verse',at:88},{name:'Chorus',at:124},{name:'Solo',at:158},{name:'Chorus',at:182},{name:'Outro',at:200}] },
    { id:'t043', title:'Salsa de Medianoche', artist:'Marisol Vega', album:'Plaza Central',
      durationSec:228, genre:'latin', mood:'energetic', tempoBpm:112, era:'2000s', energy:9,
      instruments:['trumpet','piano','percussion','bass','vocals'], sources:['spotify','youtube'],
      hue:10, sections:[{name:'Intro',at:0},{name:'Verse',at:16},{name:'Chorus',at:58},{name:'Verse',at:96},{name:'Chorus',at:134},{name:'Bridge',at:172},{name:'Chorus',at:196},{name:'Outro',at:216}] },
    { id:'t044', title:'Balada del Faro', artist:'Los Ficticios', album:'Faro Viejo',
      durationSec:241, genre:'latin', mood:'melancholy', tempoBpm:78, era:'1980s', energy:5,
      instruments:['guitar','violin','vocals'], sources:['apple'],
      hue:200, sections:[{name:'Intro',at:0},{name:'Verse',at:20},{name:'Chorus',at:64},{name:'Verse',at:104},{name:'Chorus',at:146},{name:'Bridge',at:188},{name:'Outro',at:226}] },
    { id:'t045', title:'Bossa Breeze', artist:'Marisol Vega', album:'Faro Viejo',
      durationSec:195, genre:'latin', mood:'chill', tempoBpm:92, era:'2010s', energy:6,
      instruments:['guitar','flute','percussion','vocals'], sources:['soundcloud','spotify'],
      hue:140, sections:[{name:'Intro',at:0},{name:'Verse',at:14},{name:'Chorus',at:50},{name:'Verse',at:86},{name:'Chorus',at:122},{name:'Bridge',at:158},{name:'Outro',at:182}] },

    // ---------- AMBIENT ----------
    { id:'t046', title:'Moss & Mist', artist:'Fieldnotes', album:'Slow Geography',
      durationSec:324, genre:'ambient', mood:'focus', tempoBpm:60, era:'2020s', energy:2,
      instruments:['pads','field recordings','piano'], sources:['spotify','apple','soundcloud'],
      hue:130, sections:[{name:'Intro',at:0},{name:'Verse',at:40},{name:'Chorus',at:120},{name:'Bridge',at:210},{name:'Chorus',at:270},{name:'Outro',at:308}] },
    { id:'t047', title:'Driftwood Cathedral', artist:'Fieldnotes', album:'Slow Geography',
      durationSec:298, genre:'ambient', mood:'chill', tempoBpm:64, era:'2010s', energy:3,
      instruments:['pads','strings'], sources:['youtube','local'],
      hue:210, sections:[{name:'Intro',at:0},{name:'Verse',at:36},{name:'Chorus',at:110},{name:'Bridge',at:195},{name:'Outro',at:280}] },
    { id:'t048', title:'Static Snowfall', artist:'Glacier Static', album:'Whiteout',
      durationSec:287, genre:'ambient', mood:'melancholy', tempoBpm:58, era:'2020s', energy:2,
      instruments:['pads','synth'], sources:['spotify'],
      hue:190, sections:[{name:'Intro',at:0},{name:'Verse',at:34},{name:'Chorus',at:104},{name:'Bridge',at:186},{name:'Chorus',at:240},{name:'Outro',at:272}] }
  ];

  window.KM_DATA = { tracks: TRACKS };
})();
